# {{user}}

## Written Form

```{r visualize-written-{{user}}, fig.width=12, fig.height=8}
graphs |>
  filter(SID == "{{user}}", type == "w") |>
  mutate(
    plot = map(
      graph,
      ~ ggraph(.x, layout = "igraph", algorithm = "circle") +
        geom_edge_link(aes(width = 1 / distance)) +
        geom_node_label(aes(label = name)) +
        scale_edge_width(range = c(0.1, 2), guide = "none") +
        theme_graph()
    )
  ) |>
  pull(plot) |>
  wrap_plots() +
  plot_annotation(tag_levels = "1", tag_prefix = "Time: ")
```

## Oral Form

```{r visualize-oral-{{user}}, fig.width=12, fig.height=8}
graphs |>
  filter(SID == "{{user}}", type == "o") |>
  mutate(
    plot = map(
      graph,
      ~ ggraph(.x, layout = "igraph", algorithm = "circle") +
        geom_edge_link(aes(width = 1 / distance)) +
        geom_node_label(aes(label = name)) +
        scale_edge_width(range = c(0.1, 2), guide = "none") +
        theme_graph()
    )
  ) |>
  pull(plot) |>
  wrap_plots() +
  plot_annotation(tag_levels = "1", tag_prefix = "Time: ")
```
