---
title: "Visualize Graphs"
author: "Liang Zhang"
date: "2021-07-09"
output:
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
library(tidyverse)
library(tidygraph)
library(ggraph)
library(patchwork)
library(lmerTest)
library(emmeans)
knitr::opts_knit$set(root.dir = here::here())
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
```

```{r load-data, include=FALSE}
targets::tar_load(graphs)
targets::tar_load(graph_mean)
targets::tar_load(file_child_viz_graph)
```

```{r common-funs}
vis_graph <- function(g) {
  ggraph(g, layout = "igraph", algorithm = "circle") +
    geom_edge_link(aes(width = 1 / distance)) +
    geom_node_label(aes(label = name)) +
    scale_edge_width(range = c(0.1, 2), guide = "none") +
    theme_graph()
}
```

# Visualize

Here we visualize the continuous graphs of each time point for each subject and each type of response form.

```{r render-content}
src <- purrr::map_chr(
  sort(unique(graphs$SID)),
  ~ knitr::knit_expand(file_child_viz_graph, user = .x)
)
```

`r knitr::knit(text = str_c(src, collapse = "\n\n"))`

## Averaged Graph

This is the mean of all graphs.

### Written Form

```{r graph-mean-written, fig.width=12, fig.height=8}
graph_mean |>
  filter(type == "w") |>
  mutate(plot = map(graph, vis_graph)) |>
  pull(plot) |>
  wrap_plots() +
  plot_annotation(tag_levels = "1", tag_prefix = "Time: ")
```

### Oral Form

```{r graph-mean-oral, fig.width=12, fig.height=8}
graph_mean |>
  filter(type == "o") |>
  mutate(plot = map(graph, vis_graph)) |>
  pull(plot) |>
  wrap_plots() +
  plot_annotation(tag_levels = "1", tag_prefix = "Time: ")
```

# Dynamic

```{r prepare-data-mdl}
data <- graphs |>
  mutate(
    Time = factor(Time),
    type = factor(type, c("o", "w"), c("Oral", "Written")),
    map_df(
      graph,
      ~ .x |>
        activate(nodes) |>
        mutate(strength = centrality_degree(weights = 1 / distance)) |>
        as_tibble() |>
        summarise(mean_strength = mean(strength))
    )
  )
mdl_fitted <- lmer(mean_strength ~ Time * type + (1 | SID), data)
```


```{r plot-single, fig.width=8, fig.height=6}
ggplot(data, aes(Time, mean_strength, color = type)) +
  geom_point(position = position_dodge(width = 0.2)) +
  geom_line(aes(group = type), position = position_dodge(width = 0.2)) +
  scale_color_brewer(palette = "Paired") +
  facet_wrap(~ SID, labeller = "label_both") +
  labs(y = "Mean Strength", color = "Response") +
  ggpubr::theme_pubr()
```

```{r plot-stats, fig.width=8, fig.height=6}
emmeans(mdl_fitted, ~ Time * type) |>
  broom::tidy() |>
  ggplot(aes(
    Time, estimate,
    ymin = estimate - std.error, ymax = estimate + std.error,
    color = type
  )) +
  geom_point(position = position_dodge(width = 0.2)) +
  geom_errorbar(width = 0, position = position_dodge(width = 0.2)) +
  geom_line(aes(group = type), position = position_dodge(width = 0.2)) +
  scale_color_brewer(palette = "Paired") +
  labs(y = "Mean Strength", color = "Response") +
  ggpubr::theme_pubr()
```

# Statistical Results

## ANOVA Table

```{r anova}
anova(mdl_fitted) |>
  broom::tidy() |>
  mutate(
    `F` = sprintf("F(%.0f, %.0f) = %.2f", NumDF, DenDF, statistic),
    .before = p.value,
    .keep = "unused"
  ) |>
  rstatix::p_format() |>
  rstatix::p_mark_significant() |>
  gt::gt() |>
  gt::fmt_number(ends_with("sq"))
```

## Simple Effect of Response Type

```{r simple-effect-type}
emmeans(mdl_fitted, ~ Time*type) |>
  contrast(method = "pairwise", simple = "type") |>
  broom::tidy() |>
  select(-null.value, -estimate, -std.error) |>
  mutate(
    t = sprintf("t(%.0f) = %.2f", df, statistic),
    .before = p.value,
    .keep = "unused"
  ) |>
  rstatix::p_format() |>
  rstatix::p_mark_significant() |>
  gt::gt()
```

## Simple Effect of Response Time

```{r simple-effect-time}
emmeans(mdl_fitted, ~ Time*type) |>
  contrast(method = "pairwise", simple = "Time") |>
  broom::tidy() |>
  select(-null.value, -estimate, -std.error) |>
  mutate(
    t = sprintf("t(%.0f) = %.2f", df, statistic),
    .before = adj.p.value,
    .keep = "unused"
  ) |>
  rstatix::p_format() |>
  rstatix::p_mark_significant() |>
  gt::gt()
```
